---
version: "3"

tasks:
  check-docker:
    desc: "Validate that Docker is installed and running"
    cmds:
      - |
        if ! command -v docker &> /dev/null; then
          echo "Docker is not installed. Please install Docker to continue."
          exit 1
        fi
        if ! docker info &> /dev/null; then
          echo "Docker daemon is not running. Please start Docker to continue."
          exit 1
        fi
    silent: true

  check-repository-format:
    desc: "Validate repository format matches org/repo pattern"
    cmds:
      - |
        if [[ ! "{{.REPOSITORY}}" =~ ^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$ ]]; then
          echo "Error: Repository format must be 'org/repo'. Got: {{.REPOSITORY}}"
          echo "Example: microsoft/vscode"
          exit 1
        fi
    silent: true

  renovate-docker-debug:
    desc: "Run Renovate in a Docker container with debugging enabled"
    deps:
      - check-docker
      - check-repository-format
    cmds:
      - |
        # Ensure required environment variables are set
        if [ -z "$GITHUB_TOKEN" ]; then
          echo "GITHUB_TOKEN environment variable is required"
          exit 1
        fi

        # Create cache directory if it doesn't exist
        mkdir -p .cache

        # Extract org and repo for potential use in validation
        ORG=$(echo "{{.REPOSITORY}}" | cut -d'/' -f1)
        REPO=$(echo "{{.REPOSITORY}}" | cut -d'/' -f2)

        # Additional repository existence check if requested
        if [ "{{.VALIDATE_REPO | default "true"}}" = "true" ] && [ "{{.PLATFORM | default "github"}}" = "github" ]; then
          if ! gh repo view "{{.REPOSITORY}}" &>/dev/null; then
            echo "Error: Repository {{.REPOSITORY}} not found or not accessible"
            exit 1
          fi
        fi

        # Run Renovate in Docker with configurable parameters
        docker run --rm -it \
          -e LOG_LEVEL="{{.LOG_LEVEL | default "debug"}}" \
          -e RENOVATE_LOCAL_DIR="/tmp/renovate/repository" \
          -e RENOVATE_CONFIG_FILE="/usr/src/app/renovate.json5" \
          -e RENOVATE_DEBUG="{{.DEBUG | default "true"}}" \
          -e RENOVATE_PLATFORM_COMMIT="{{.PLATFORM_COMMIT | default "true"}}" \
          -e RENOVATE_ONBOARDING_CONFIG_FILE_NAME="{{.CONFIG_FILE_NAME | default ".github/renovate.json5"}}" \
          -e RENOVATE_BASE_DIR="/tmp/renovate/repository" \
          -e RENOVATE_GIT_AUTHOR="{{.GIT_AUTHOR | default "Renovate Bot <bot@renovateapp.com>"}}" \
          -e RENOVATE_TOKEN="${GITHUB_TOKEN}" \
          -e RENOVATE_PLATFORM="{{.PLATFORM | default "github"}}" \
          -e RENOVATE_ENDPOINT="{{.ENDPOINT | default "https://api.github.com"}}" \
          -e RENOVATE_REPOSITORY="{{.REPOSITORY}}" \
          -e RENOVATE_FORK="{{.FORK | default "false"}}" \
          -v "${PWD}/{{.CONFIG_FILE_PATH | default ".github/renovate.json5"}}:/usr/src/app/renovate.json5" \
          -v "${PWD}:/tmp/renovate/repository" \
          -v "${PWD}/.cache:/tmp/renovate/cache" \
          --user=$(id -u):$(id -g) \
          {{.RENOVATE_IMAGE | default "ghcr.io/renovatebot/renovate:latest"}} \
          {{.REPOSITORY}} | tee {{.LOG_FILE | default "renovate-debug.log"}}
    requires:
      vars: ["REPOSITORY"]
