version: "3"

tasks:
  default:
    desc: "Show current release version"
    cmds:
      - echo "Release version {{.APP_TAG}}"
    silent: true

  major:
    desc: "Increase major version"
    run: once
    cmds:
      - "{{ .PYTHON_PACKAGE_MANAGER }} version major"

  minor:
    desc: "Increase minor version"
    run: once
    cmds:
      - "{{ .PYTHON_PACKAGE_MANAGER }} version minor"

  patch:
    desc: "Increase patch version"
    run: once
    cmds:
      - "{{ .PYTHON_PACKAGE_MANAGER }} version patch"
