---
version: "3"

includes:
  changelog: ./src/changelog/Taskfile.yml
  confluence: ./src/confluence/Taskfile.yml
  uv: ./src/uv/Taskfile.yml
  python: ./src/python/Taskfile.yml
  git: ./src/git/Taskfile.yml
  docs: ./src/docs/Taskfile.yml
  docker: ./src/docker/Taskfile.yml
  version: ./src/version/Taskfile.yml
  plantuml: ./src/plantuml/Taskfile.yml
  prettier: ./src/prettier/Taskfile.yml
  sonar: ./src/sonar/Taskfile.yml
  diagrams: ./provision/diagrams/Taskfile.yml

env:
  DOCKER:
    sh: docker --version 2> /dev/null || echo "not exist"
  PYTHON:
    sh: python --version 2> /dev/null || echo "not exist"
  GO:
    sh: go version 2> /dev/null || echo "not exist"
  NODE:
    sh: node --version 2> /dev/null || echo "not exist"
  APP_TAG:
    sh: git describe --tags $(git rev-list --tags --max-count=1) 2> /dev/null || echo "0.0.0"
  PYTHON_PACKAGE_MANAGER: uv
  README_YAML: provision/generators/README.yaml
  README_TEMPLATE: provision/templates/README.tpl.md
  README_INCLUDES: file://
  TERRAFORM_PATH: ./

dotenv:
  - .env

vars:
  PROJECT_NAME: tasks
  ORGANIZATION: hadenlabs
  DOCKER_PLATFORM: linux/amd64
  REVIEWERS: luismayta
  PYTHON_VERSION: 3.11.5
  NODE_VERSION: v20.18.3
  GIT_IGNORES: python,node,go,zsh,sonar,java,maven,intellij+all,terraform,linux
  GOLANGCI_VERSION: 1.42.0
  TERRAFORM_VERSION: 1.10.5
  README_FILE: README.md
  ANSIBLE_COLLECTIONS: |
    community.sops
  GIT_IGNORES_CUSTOM: |
    bin
    .scannerwork
    .secrets
    public
    TMP_CHANGELOG.md
    .task
    .terraform.lock.hcl
    *.lock.hcl
    *.lock
    *.zip
    .external_modules
    vendor
    charts
    .DS_Store

tasks:
  default:
    deps:
      - task: check
    cmds:
      - cmd: echo Application {{.PROJECT_NAME}}
        silent: true
      - task: version:default
      - task: summary
      - cmd: task -l
    silent: true

  summary:
    desc: "Summary information"
    cmds:
      - echo Go available {{.GO}}
      - echo Python available {{.PYTHON}}
      - echo Docker available {{.DOCKER}}
      - echo Node available {{.NODE}}
    silent: true

  check:
    desc: "Check all dependencies"
    deps:
      - uv:check
      - changelog:check
      - git:check
      - docs:check

  readme:
    desc: Generate Readme
    silent: true
    cmds:
      - >-
        gomplate --file {{.README_TEMPLATE}}
        --out {{.README_FILE}}
        --datasource config={{.README_YAML}}
        --datasource includes={{.README_INCLUDES}}
      - task: prettier

  prettier:
    desc: Execute prettier files
    cmds:
      - task: prettier:all

  upgrade:
    desc: Execute upgrade packages
    cmds:
      - uv update
      - uv run pre-commit autoupdate

  setup:
    desc: Setup dependences of project
    cmds:
      - >-
        [ -e ".env" ] || cp -rf .env.example .env
      - task: uv:setup
      - task: uv:precommit
      - task: git:setup

  test:
    run: once
    desc: Execute task test all
    cmds:
      - task: go:test

  environment:
    desc: Setup environment of project
    cmds:
      - task: uv:environment
