---
version: "3"

tasks:
  check:
    desc: Exist python and dependences
    run: once
    deps:
      - task: check:uv

  check:uv:
    desc: Exist uv
    run: once
    preconditions:
      - sh: command -v uv
        msg: "Please Install uv"

  update:
    desc: "Update pre-commit hooks"
    cmds:
      - uvx pre-commit autoupdate
    deps:
      - task: check:uv

  clear:
    desc: "Clear pre-commit cache"
    cmds:
      - uvx pre-commit clean
    deps:
      - task: check

  lint:
    desc: "Run all pre-commit hooks locally"
    cmds:
      - uvx pre-commit run --all-files
    deps:
      - task: check

  setup:
    desc: Install pre-commit.
    run: once
    cmds:
      - uvx pre-commit install
      - uvx pre-commit install -t pre-push
      - uvx pre-commit install -t commit-msg
      - uvx pre-commit install -t prepare-commit-msg
    deps:
      - task: check