---
version: "3"

tasks:
  default:
    desc: List all available tasks
    cmds:
      - task -t src/uv/Taskfile.yml --list

  check:
    desc: Exist python and dependences
    run: once
    deps:
      - task: check:python
      - task: check:uv
      - task: check:ruff
      - task: check:curl

  check:curl:
    desc: Exist curl
    run: once
    preconditions:
      - sh: command -v curl
        msg: "Please Install curl"

  check:python:
    desc: Exist Python
    run: once
    preconditions:
      - sh: command -v python
        msg: "Please Install python"

  check:uv:
    desc: Exist uv
    run: once
    preconditions:
      - sh: command -v uv
        msg: "Please Install uv"

  check:ruff:
    desc: Exist ruff
    run: once
    preconditions:
      - sh: test "uv run command -v ruff"
        msg: "Please Install ruff"

  _setup:
    desc: Install uv if not present
    run: once
    cmds:
      - cmd: '[ -n "$(command -v uv)" ] || curl -LsSf https://astral.sh/uv/install.sh | sh'
        silent: true
    deps:
      - task: check:curl

  setup:
    desc: Setup python dependences.
    run: once
    cmds:
      - uv sync --all-groups
    deps:
      - task: check:python
      - task: _setup

  fmt:
    desc: format ruff
    run: once
    cmds:
      - cmd: >-
          uvx ruff format ./ {{.CLI_ARGS}}

  lint:
    desc: Lint with ruff
    cmds:
      - uvx ruff check ./ {{.CLI_ARGS}}
      - task: mypy

  test:
    desc: run pytest.
    run: once
    cmds:
      - task: pytest

  pytest:
    desc: Run tests with pytest and coverage
    cmds:
      - uvx coverage run -m pytest -s -vv
      - uvx coverage report
      - uvx coverage html

  mypy:
    desc: Run mypy types checking
    cmds:
      - uvx mypy src

  environment:
    desc: Generate environment python.
    run: once
    cmds:
      - uv python install
    deps:
      - task: check:uv
