version: "3"

tasks:
  check:
    desc: Exist pnpm and dependences
    run: once
    deps:
      - task: check:pnpm
      - task: check:curl

  check:pnpm:
    desc: Exist pnpm
    run: once
    preconditions:
      - sh: command -v pnpm
        msg: "Please Install pnpm"

  check:curl:
    desc: Exist curl
    run: once
    preconditions:
      - sh: command -v curl
        msg: "Please Install curl"


  setup:
    desc: Setup pnpm dependences.
    run: once
    cmds:
      - pnpm install
    deps:
      - task: check:pnpm

  update:
    desc: Update pnpm.
    run: once
    cmds:
      - pnpm run ncu:patch
    deps:
      - task: check:pnpm

  environment:
    desc: Install pnpm if not present
    run: once
    cmds:
      - cmd: '[ -n "$(command -v pnpm)" ] || curl -fsSL https://get.pnpm.io/install.sh | sh -'
        silent: true
    deps:
      - task: check:curl





