version: "3"

tasks:
  check:
    desc: Exist Yarn and dependences
    run: once
    deps:
      - task: check:yarn
      - task: check:fnm

  check:yarn:
    desc: Exist Yarn
    run: once
    preconditions:
      - sh: command -v yarn
        msg: "Please Install yarn"

  check:fnm:
    desc: Exist Nvm
    run: once
    preconditions:
      - sh: test "command -v fnm"
        msg: "Please Install fnm"

  setup:
    desc: Setup yarn dependences.
    run: once
    cmds:
      - yarn install
    deps:
      - task: check:yarn

  update:
    desc: Update yarn.
    run: once
    cmds:
      - yarn ncu:patch
    deps:
      - task: check:yarn

  environment:
    desc: Setup environment fnm version node.
    run: once
    cmds:
      - fnm use {{.NODE_VERSION}}
    deps:
      - task: check
